export const ROUTES = {
  HOME: "/",
  AUTH: {
    LOGIN: "/login",
  },
  ERP: {
    DASHBOARD: "/dashboard",
    CALENDAR: "/calendar",
    REPORTS: {
      OVERVIEW: "/reports",
      REVENUE: "/reports/revenue",
      EXPENSES: "/reports/expenses",
      PROFIT: "/reports/profit",
      PROJECTS: "/reports/projects",
      CUSTOMERS: "/reports/customers",
      EMPLOYEES: "/reports/employees",
    },
    CUSTOMERS: "/customers",
    LEADS: "/leads",
    QUOTATIONS: "/quotations",
    CONTRACTS: "/contracts",
    DOCUMENT_TEMPLATES: "/document-templates",
    PROJECTS: "/projects",
    TASKS: "/tasks",
    WORKERS: "/workers",
    ACCEPTANCE_REPORTS: "/acceptance-reports",
    LIQUIDATION_REPORTS: "/liquidation-reports",
    INVENTORY: {
      OVERVIEW: "/inventory",
      MATERIALS: "/inventory/materials",
      STOCK_IN: "/inventory/stock-in",
      STOCK_OUT: "/inventory/stock-out",
      MOVEMENTS: "/inventory/movements",
    },
    SUPPLIERS: "/suppliers",
    RECEIPTS: "/receipts",
    PAYMENTS: "/payments",
    DEBTS: "/debts",
    VAT_INVOICES: "/vat-invoices",
    ONLINE_SALES: {
      PRODUCTS: "/online-sales/products",
      ORDERS: "/online-sales/orders",
    },
    OMNICHANNEL: {
      INBOX: "/omnichannel/inbox",
      FACEBOOK: "/omnichannel/facebook",
      ZALO: "/omnichannel/zalo",
    },
    SETTINGS: {
      OVERVIEW: "/settings",
      COMPANY: "/settings/company",
      USERS: "/settings/users",
      ROLES: "/settings/roles",
      FINANCE: "/settings/finance",
      SALES: "/settings/sales",
      PROJECTS: "/settings/projects",
      INVENTORY: "/settings/inventory",
      DOCUMENTS: "/settings/documents",
      NOTIFICATIONS: "/settings/notifications",
      SECURITY: "/settings/security",
      AUDIT_LOGS: "/settings/audit-logs",
      BACKUPS: "/settings/backups",
    },
  },
} as const;

export type AppRoutes = typeof ROUTES;
